

```{r}
library(JuliaCall)
library(diffeqr)
library(ggplot2)
library(dplyr)
library(tidyr)
```

Set up Julia with local filepath
```{r}
julia_setup(JULIA_HOME = "/Applications/Julia-1.10.app/Contents/Resources/julia/bin")

```


```{r}
source("src/emude.R")
ude <- emude_setup()
```


```{r}
# source("src/model_constructors.R")
data <- data.frame(time = 1:10, x = rnorm(10))
UDE2 <- ude$NODE(data)

```

```{r}
source("src/helpers.R")

parameters <- list(r = 1.0)

dudt <- function(u,nn,p,t){
    p$r*u[1]*nn[1]
}

julia_assign("dudt", dudt)
```

```{r}
julia_eval("dudt([1.0],[0.5],(r=1.0,))")
```


```{r}
julia_eval("print(UDE_jl.data)")
```


```{r}
build_UDE_R <- function(UDE){
    julia_assign("UDE_jl", UDE)
    UDE_R <- list(data = julia_eval("UDE_jl.data"), 
                parameters = julia_eval("UDE_jl.parameters"),
                model = UDE)
    class(UDE_R) <- "UDE"
    return(UDE_R)
}
UDE_R
```

```{r}
get_parameters <- function(UDE){
    julia_assign("UDE_jl", UDE)
    julia_eval("UDE_jl.parameters")
}
```

```{r}
df <- sapply(UDE,identity)
```

```{r}
get_right_hand_side <- function(UDE){
    julia_assign("UDE_jl", UDE)
    julia_eval("UDE_jl")

    dudt <- function(u,t){
        julia_assign("u_jl", u)
        julia_assign("t_jl", t)
        julia_eval("typeof(u_jl) == ")
        julia_eval("println(typeof(u_jl))")
        julia_eval("UDE_jl.process_model.rhs(u_jl,UDE_jl.parameters.process_model,t_jl)")
    }

    return(dudt)
}

rhs <- get_right_hand_side(UDE)
```

```{r}
plot_predict(UDE)
```

```{r}
UDE_R$parameters
```