JuliaCall::julia_setup(installJulia = TRUE)
JuliaCall::julia_install_package_if_needed("UniversalDiffEq")
JuliaCall::julia_install_package_if_needed("ComponentArrays")
JuliaCall::julia_install_package_if_needed("Lux")
JuliaCall::julia_install_package_if_needed("Random")
JuliaCall::julia_install_package_if_needed("DiffEqFlux")
JuliaCall::julia_install_package_if_needed("DataFrames")
JuliaCall::julia_library("UniversalDiffEq")
JuliaCall::julia_library("ComponentArrays")
JuliaCall::julia_library("Lux")
JuliaCall::julia_library("Random")
JuliaCall::julia_library("DiffEqFlux")
JuliaCall::julia_library("DataFrames")
